version: '2'
services:
    mysql1:
        image: mysql:5.7.20
        volumes:
            - db:/var/lib/mysql/
            - ./test/fixtures/samples/db:/docker-entrypoint-initdb.d
        environment:
            - TZ=Asia/Shanghai
            - MYSQL_ROOT_PASSWORD=654321
            - MYSQL_DATABASE=dev
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=123456
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp


volumes:
    db:
